### PR TITLE
Add goto button in browser

### PR DESCRIPTION
**Pull request by ReDetection**
Sometimes I already have url, but it's uncomfortable to search video by title, so I made a goto button.

P.s. it seems https url scheme can't be assigned to app, only custom ones, so the only way to make it more handy is Share Extensions which require much more work to do. Maybe some day..

### CODE REVIEW

**Comment by ReDetection** [comment]
> you can search for videos with the url if you delete everything but the identifier

Oh, cool, never knew that. Nice. It even works with full url, which provides basically the same functionality, except it does not work for playlists.

Custom URL scheme is a way to make deeplink so system knows that link `myApp://blabla/` should be opened in particular app. However, we only have https youtube url, so we can't do that because http/https can't be assigned to the app.

Share extension is like a plugin to the system so it can ask if you can handle something or not. In example, in the browser you can tap share button at the bottom, it will offer some options and apps to handle that URL. Initially invented to share to others, that's why it's called like this. But because that plugin is basically other program, and it needs to access app's data, this requires App Groups capability to be used, and probably implementing background download.

**Comment by samuelechu** [comment]
That's pretty cool, I never heard about this stuff! So you're saying that the custom URL wouldn't be too useful because the user would have to type in myApp://(youtubelink)/? Yeah the share extension thing sounds interesting. So clicking on the share extension button within a browser like safari would start a download on the app? Maybe if the user opens a video link with the share button, we can also save it onto a playlist on the user's channel so that it can be downloaded later.

**Comment by ReDetection** [comment]
Oh, I don't expect anyone to type something :) I'm too lazy to type something so often.

>So clicking on the share extension button within a browser like safari would start a download on the app? 
Exactly.

Well, playlist is also a solution. 👍

**Comment by ReDetection** [comment]
Oh, I cannot use search field to open unlisted video. OK, maybe it's time to invest some time into share function..

**Pull request closed without merging**
